# https://hub.docker.com/_/odoo/
version: '3.1'
services:
  web:
    image: odoo:16.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ../addons:/mnt/extra-addons
    environment:
    - HOST=host.docker.internal
    - USER=odoo
    - PASSWORD=myodoo
    command: --dev=all 

volumes:
  odoo-web-data:
